import { randomBytes } from 'node:crypto';
import type { OnboardingApplication, OperationsRequest } from '@prisma/client';
import {
  ONBOARDING_PRODUCT_LABELS,
  type NormalizedOpenAccount,
  type OnboardingApplicationSummary,
  type OnboardingProduct,
  type OnboardingStatus,
  type OperationsRequestDTO,
  type SimulatedEventDTO,
} from '@simbank/shared';
import { prisma, type DbClient } from '../db';
import { hashPassword } from '../auth/password';
import { writeAudit } from '../auth/audit';
import { createInvitationRecord } from './invitations';
import { toOperationsRequestDTO, toSimulatedEventDTO } from './requests';

/**
 * Onboarding & account-opening domain service (v0.6.0).
 *
 * The flow has two halves, deliberately split so an operator approval is what
 * makes onboarding "real":
 *
 *  1. `submitApplication` (PUBLIC) — records a fake application + a linked
 *     `OperationsRequest` (type `onboarding`) on the SAME queue v0.5.0 built, and
 *     emits clearly-labelled SIMULATED identity/MFA/email events. It creates NO
 *     user, NO account, and NO money.
 *  2. `provisionApprovedOnboarding` — runs only when an operator APPROVES that
 *     request (see `applyOperatorAction`). It creates the `User` + `Account` +
 *     owner grant and, if the applicant chose an opening deposit, posts it as an
 *     explicit BANK-ORIGINATED, posted `deposit` ledger entry (audited). Balances
 *     stay DERIVED — value only ever enters via this bank-originated event.
 */

const AUDIT_ENTITY_REQUEST = 'operations_request';
const AUDIT_INTAKE_ACTION = 'ops_request_created';

/** A short, human-friendly application reference (SIMULATION code). */
export function generateReference(): string {
  return `MER-${randomBytes(3).toString('hex').toUpperCase()}`;
}

/** Map an application row to the operator-facing summary (NEVER the password hash). */
export function toOnboardingApplicationSummary(
  row: OnboardingApplication,
): OnboardingApplicationSummary {
  return {
    reference: row.reference,
    fullName: row.fullName,
    email: row.email,
    product: row.product as OnboardingProduct,
    initialFundingMinor: row.initialFundingMinor,
    jointInviteEmail: row.jointInviteEmail,
    status: row.status as OnboardingStatus,
  };
}

/** Create a clearly-labelled SIMULATED event row and return its DTO. */
async function recordSimEvent(
  db: DbClient,
  input: {
    channel: SimulatedEventDTO['channel'];
    kind: string;
    status: SimulatedEventDTO['status'];
    direction?: SimulatedEventDTO['direction'];
    summary: string;
    detail?: string;
    requestId: string | null;
  },
  now: Date,
): Promise<SimulatedEventDTO> {
  const created = await db.simulatedEvent.create({
    data: {
      channel: input.channel,
      direction: input.direction ?? 'outbound',
      kind: input.kind,
      status: input.status,
      summary: input.summary,
      detail: input.detail ?? 'SIMULATION — no real message was sent to any provider.',
      requestId: input.requestId,
      createdAt: now,
    },
  });
  return toSimulatedEventDTO(created);
}

export interface SubmittedApplication {
  reference: string;
  request: OperationsRequestDTO;
  /** SIMULATED events generated by intake (for the route to broadcast). */
  events: SimulatedEventDTO[];
}

/**
 * Submit a (simulated) account-opening application: hash the chosen password,
 * create the application + its linked `onboarding` queue item, write the intake
 * audit row, and generate the onboarding identity/MFA/email SIMULATED events.
 * Creates no user/account/money — provisioning happens only on operator approval.
 */
export async function submitApplication(
  input: NormalizedOpenAccount,
  now: Date = new Date(),
): Promise<SubmittedApplication> {
  const reference = generateReference();
  const passwordHash = await hashPassword(input.password);
  const productLabel = ONBOARDING_PRODUCT_LABELS[input.product];

  const request = await prisma.operationsRequest.create({
    data: {
      type: 'onboarding',
      status: 'pending',
      priority: 'normal',
      summary: `New account application — ${productLabel}`,
      detail: `A prospective customer applied to open a ${productLabel} account (simulated). Approving this request provisions the account and posts any opening deposit.`,
      subjectName: input.fullName,
      subjectEmail: input.email,
      payload: JSON.stringify({
        reference,
        product: input.product,
        initialFundingMinor: input.initialFundingMinor,
        jointInviteEmail: input.jointInviteEmail,
      }),
      createdAt: now,
      updatedAt: now,
    },
  });

  await prisma.onboardingApplication.create({
    data: {
      reference,
      status: 'submitted',
      fullName: input.fullName,
      email: input.email,
      product: input.product,
      initialFundingMinor: input.initialFundingMinor,
      jointInviteEmail: input.jointInviteEmail,
      consentAt: now,
      passwordHash,
      requestId: request.id,
      createdAt: now,
      updatedAt: now,
    },
  });

  // Intake audit row (mirrors the seed so the request-detail history reads
  // "created → …" from the same AuditLog trail operator actions append to).
  await writeAudit(prisma, {
    actorRole: 'system',
    action: AUDIT_INTAKE_ACTION,
    entity: AUDIT_ENTITY_REQUEST,
    entityId: request.id,
    reason: `Application ${reference} received (simulated)`,
    metadata: { reference, product: input.product },
  });

  // Onboarding SIMULATED events — the first real use of the simulated-messaging
  // seam: an application-received notice + an identity check + an MFA enrollment,
  // all clearly fake and linked to the queue item.
  const events: SimulatedEventDTO[] = [];
  events.push(
    await recordSimEvent(
      prisma,
      {
        channel: 'email',
        kind: 'application_received',
        status: 'sent',
        summary: `Application received — under review (simulated)`,
        detail: `Simulated email confirming application ${reference} was received.`,
        requestId: request.id,
      },
      now,
    ),
  );
  events.push(
    await recordSimEvent(
      prisma,
      {
        channel: 'identity',
        kind: 'verification',
        status: 'pending',
        summary: 'Identity verification requested (simulated)',
        detail: 'Simulated identity-verification step for a new account application.',
        requestId: request.id,
      },
      now,
    ),
  );
  events.push(
    await recordSimEvent(
      prisma,
      {
        channel: 'mfa',
        kind: 'enrollment',
        status: 'pending',
        summary: 'MFA enrollment offered (simulated)',
        detail: 'Simulated multi-factor enrollment offered to the new applicant.',
        requestId: request.id,
      },
      now,
    ),
  );

  return { reference, request: toOperationsRequestDTO(request), events };
}

export interface ProvisionResult {
  userId: string;
  accountId: string;
  fundingMinor: number;
  invitationId: string | null;
  /** SIMULATED events generated by provisioning (for the route to broadcast). */
  events: SimulatedEventDTO[];
}

/**
 * Pre-flight check run BEFORE an onboarding request is marked approved: is the
 * application present, still submitted, and is its email free to provision?
 * Returns a reason string when provisioning must be blocked, else null.
 */
export async function onboardingApprovalBlocker(
  request: Pick<OperationsRequest, 'id' | 'type'>,
): Promise<string | null> {
  if (request.type !== 'onboarding') return null; // not an onboarding request → nothing to provision
  const application = await prisma.onboardingApplication.findUnique({
    where: { requestId: request.id },
  });
  if (!application) return null; // a seeded/legacy onboarding item with no application — approve as a plain workflow item
  if (application.status !== 'submitted') {
    return 'This application has already been provisioned or rejected.';
  }
  const existing = await prisma.user.findUnique({ where: { email: application.email } });
  if (existing) {
    return `A user with the email ${application.email} already exists; cannot provision this application.`;
  }
  return null;
}

/**
 * Provision an approved onboarding application: create the User + Account + owner
 * access, post any opening deposit as a BANK-ORIGINATED `deposit` ledger entry
 * (audited), optionally create a joint-owner invitation, and mark the application
 * provisioned. MUST run inside a transaction (`tx`) so it is atomic with the
 * request's status change. Returns the ids + the SIMULATED events to broadcast.
 *
 * No-ops (returns null) for an onboarding request that has no linked application
 * (e.g. a seeded workflow-only item) — such a request just approves as before.
 */
export async function provisionApprovedOnboarding(
  tx: DbClient,
  requestId: string,
  actor: { id: string; role: string; displayName: string },
  now: Date,
): Promise<ProvisionResult | null> {
  const application = await tx.onboardingApplication.findUnique({ where: { requestId } });
  if (!application || application.status !== 'submitted') return null;

  const product = application.product as OnboardingProduct;
  const accountName = ONBOARDING_PRODUCT_LABELS[product] ?? application.product;

  // 1) The user (role customer; the hashed password captured at apply time).
  const user = await tx.user.create({
    data: {
      email: application.email,
      displayName: application.fullName,
      role: 'customer',
      status: 'active',
      passwordHash: application.passwordHash,
      passwordUpdatedAt: now,
    },
  });

  // 2) The account + an explicit owner access grant (what RBAC reads).
  const account = await tx.account.create({
    data: { userId: user.id, type: product, name: accountName, openedAt: now },
  });
  await tx.accountAccess.create({
    data: { userId: user.id, accountId: account.id, relationship: 'owner' },
  });

  // 3) Initial funding — money enters ONLY via this bank-originated, posted
  //    `deposit` ledger entry. Balances remain derived; nothing is stored.
  if (application.initialFundingMinor > 0) {
    await tx.ledgerEntry.create({
      data: {
        accountId: account.id,
        amountMinor: application.initialFundingMinor,
        direction: 'credit',
        status: 'posted',
        origin: 'deposit',
        description: 'Opening deposit (simulated)',
        postedAt: now,
        createdAt: now,
      },
    });
    await writeAudit(tx, {
      actorId: actor.id,
      actorRole: actor.role,
      action: 'onboarding_initial_funding',
      entity: 'ledger_entry',
      entityId: account.id,
      reason: `Initial funding for ${application.reference} (simulated bank-originated deposit)`,
      metadata: { amountMinor: application.initialFundingMinor, origin: 'deposit', accountId: account.id },
    });
  }

  // 4) Optional joint-owner invitation (delivered only as a simulated email).
  const events: SimulatedEventDTO[] = [];
  let invitationId: string | null = null;
  if (application.jointInviteEmail) {
    const invitation = await createInvitationRecord(
      tx,
      {
        accountId: account.id,
        invitedById: user.id,
        inviteeEmail: application.jointInviteEmail,
        relationship: 'joint',
      },
      now,
    );
    invitationId = invitation.id;
    events.push(
      await recordSimEvent(
        tx,
        {
          channel: 'email',
          kind: 'invitation',
          status: 'sent',
          summary: `Joint-owner invitation sent to ${application.jointInviteEmail} (simulated)`,
          requestId,
        },
        now,
      ),
    );
  }

  // 5) Mark the application provisioned + audit the whole event.
  await tx.onboardingApplication.update({
    where: { id: application.id },
    data: { status: 'provisioned', provisionedUserId: user.id, provisionedAccountId: account.id, updatedAt: now },
  });
  await writeAudit(tx, {
    actorId: actor.id,
    actorRole: actor.role,
    action: 'onboarding_provisioned',
    entity: 'onboarding_application',
    entityId: application.id,
    reason: `Provisioned ${accountName} for ${application.email} (simulated)`,
    metadata: { userId: user.id, accountId: account.id, reference: application.reference },
  });

  // 6) A clearly-labelled "account opened" simulated event for the console feed.
  events.unshift(
    await recordSimEvent(
      tx,
      {
        channel: 'identity',
        kind: 'verification',
        status: 'approved',
        summary: `Identity verified — ${accountName} opened (simulated)`,
        detail: `Simulated: application ${application.reference} approved; account opened${
          application.initialFundingMinor > 0 ? ' and funded' : ''
        }.`,
        requestId,
      },
      now,
    ),
  );

  return { userId: user.id, accountId: account.id, fundingMinor: application.initialFundingMinor, invitationId, events };
}

/**
 * Mark an onboarding application rejected when its request is rejected, and emit
 * a simulated "declined" email. No-ops for a request with no linked application.
 */
export async function rejectOnboardingApplication(
  tx: DbClient,
  requestId: string,
  now: Date,
): Promise<SimulatedEventDTO | null> {
  const application = await tx.onboardingApplication.findUnique({ where: { requestId } });
  if (!application || application.status !== 'submitted') return null;
  await tx.onboardingApplication.update({
    where: { id: application.id },
    data: { status: 'rejected', updatedAt: now },
  });
  return recordSimEvent(
    tx,
    {
      channel: 'email',
      kind: 'notification',
      status: 'sent',
      summary: `Application ${application.reference} declined (simulated)`,
      requestId,
    },
    now,
  );
}
