#!/usr/bin/env bash
# Prepare the pinned SSH client configuration for the Meridian deployment
# account on the runner. Secrets arrive ONLY through the environment (never as
# arguments) and are never printed.
#
#   LIGHTSAIL_HOST=… LIGHTSAIL_USER=deploy-meridian \
#   SSH_PRIVATE_KEY=… SSH_KNOWN_HOSTS=… scripts/deploy/ssh-setup.sh <ssh-dir>
#
# Writes <ssh-dir>/{id_meridian (0600), known_hosts, config}. The config pins
# the host key (StrictHostKeyChecking yes + the provided known_hosts only; no
# accept-new, no ssh-keyscan), uses only this key, and never prompts.
# Remove the directory with ssh-cleanup.sh in an always() step.
set -Eeuo pipefail
export LOG_TAG="ssh-setup"
# shellcheck source=lib/common.sh
source "$(dirname -- "${BASH_SOURCE[0]}")/lib/common.sh"

[[ $# -eq 1 ]] || die "usage: ssh-setup.sh <ssh-dir>"
ssh_dir="$1"

missing=()
[[ -n "${LIGHTSAIL_HOST:-}" ]] || missing+=("repository variable LIGHTSAIL_HOST")
[[ -n "${LIGHTSAIL_USER:-}" ]] || missing+=("repository variable LIGHTSAIL_USER")
[[ -n "${SSH_PRIVATE_KEY:-}" ]] || missing+=("repository secret LIGHTSAIL_SSH_PRIVATE_KEY")
[[ -n "${SSH_KNOWN_HOSTS:-}" ]] || missing+=("repository secret LIGHTSAIL_KNOWN_HOSTS")
if ((${#missing[@]} > 0)); then
  for m in "${missing[@]}"; do log "missing: ${m}"; done
  die "required GitHub Actions configuration is missing (Settings → Secrets and variables → Actions)"
fi
# Only a plain host name or address: nothing that could inject ssh_config lines.
[[ "${LIGHTSAIL_HOST}" =~ ^[A-Za-z0-9][A-Za-z0-9.:-]*$ ]] || die "LIGHTSAIL_HOST is not a plain host name or IP address"
[[ "${LIGHTSAIL_USER}" == "${MERIDIAN_DEPLOY_USER}" ]] \
  || die "LIGHTSAIL_USER must be ${MERIDIAN_DEPLOY_USER} (the Meridian deployment account), got '${LIGHTSAIL_USER}'"

umask 077
[[ ! -e "${ssh_dir}" ]] || die "${ssh_dir} already exists"
mkdir -p "${ssh_dir}"
chmod 0700 "${ssh_dir}"
key_file="${ssh_dir}/id_meridian"
known_hosts="${ssh_dir}/known_hosts"
config="${ssh_dir}/config"

# Written exactly as provided (plus the final newline OpenSSH requires if it
# was pasted without one). printf is a shell builtin: the secret never appears
# in a process list.
write_exact() { # <value> <file>
  if [[ "$1" == *$'\n' ]]; then printf '%s' "$1" > "$2"; else printf '%s\n' "$1" > "$2"; fi
  chmod 0600 "$2"
}
write_exact "${SSH_PRIVATE_KEY}" "${key_file}"
write_exact "${SSH_KNOWN_HOSTS}" "${known_hosts}"

# The key must be a usable, passphrase-less private key (output discarded).
if ! ssh-keygen -y -P '' -f "${key_file}" > /dev/null 2>&1; then
  die "LIGHTSAIL_SSH_PRIVATE_KEY is not a usable, passphrase-less OpenSSH private key"
fi
# Public fingerprint only — safe to log, and the quickest way to spot a key
# that does not match server/apps/meridian/deploy-key.pub in the infrastructure.
log "deployment key: $(ssh-keygen -l -f "${key_file}" | awk '{print $1, $2, $NF}')"
if ! ssh-keygen -F "${LIGHTSAIL_HOST}" -f "${known_hosts}" > /dev/null 2>&1; then
  die "LIGHTSAIL_KNOWN_HOSTS contains no host key entry for LIGHTSAIL_HOST (${LIGHTSAIL_HOST})"
fi

cat > "${config}" << CONFIG
# Generated by scripts/deploy/ssh-setup.sh — Meridian deployment only.
Host meridian
    HostName ${LIGHTSAIL_HOST}
    User ${MERIDIAN_DEPLOY_USER}
    Port 22
    IdentityFile ${key_file}
    IdentitiesOnly yes
    IdentityAgent none
    UserKnownHostsFile ${known_hosts}
    GlobalKnownHostsFile /dev/null
    StrictHostKeyChecking yes
    UpdateHostKeys no
    CheckHostIP no
    BatchMode yes
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    ForwardAgent no
    ForwardX11 no
    ClearAllForwardings yes
    ControlMaster no
    ControlPath none
    ConnectTimeout 30
    ServerAliveInterval 30
    ServerAliveCountMax 4
CONFIG
chmod 0600 "${config}"
log "SSH configuration ready for ${MERIDIAN_DEPLOY_USER}@${LIGHTSAIL_HOST} (strict host key checking, pinned known_hosts)"
